import { type Request, type Response, type NextFunction } from "express";
import { eq, and, desc } from "drizzle-orm";
import { db } from "../db/index.js";
import { guestPasses } from "../models/schema.js";

/**
 * 🎫 Get guest passes generated by resident
 */
export async function getResidentGuestPasses(req: Request, res: Response, next: NextFunction) {
  try {
    if (!req.user || !req.societyId) {
      return res.status(401).json({ error: "Authentication required" });
    }

    const list = await db
      .select()
      .from(guestPasses)
      .where(
        and(
          eq(guestPasses.societyId, req.societyId),
          eq(guestPasses.residentId, req.user.id)
        )
      )
      .orderBy(desc(guestPasses.createdAt));

    return res.status(200).json({ guestPasses: list });
  } catch (error) {
    next(error);
  }
}

/**
 * ✍️ Create a pre-approved guest pass
 */
export async function createGuestPass(req: Request, res: Response, next: NextFunction) {
  try {
    if (!req.user || !req.societyId) {
      return res.status(401).json({ error: "Authentication required" });
    }

    const { guestName, validFrom, validTo } = req.body;

    if (!guestName) {
      return res.status(400).json({ error: "Guest name is required" });
    }

    // Generate secure 6-char token pass code
    const token = Math.random().toString(36).substring(2, 8).toUpperCase();

    const fromDate = validFrom ? new Date(validFrom) : new Date();
    const toDate = validTo ? new Date(validTo) : new Date(Date.now() + 86400000); // 24h validity fallback

    const [newPass] = await db
      .insert(guestPasses)
      .values({
        societyId: req.societyId,
        residentId: req.user.id,
        guestName: guestName.trim(),
        validFrom: fromDate,
        validTo: toDate,
        token,
        isUsed: false,
      })
      .returning();

    return res.status(201).json({
      message: "Pre-approved guest pass created successfully",
      guestPass: newPass,
    });
  } catch (error) {
    next(error);
  }
}
