import { type Request, type Response, type NextFunction } from "express";
import { eq, and, desc } from "drizzle-orm";
import { db } from "../db/index.js";
import { guestPasses, visitors, user } from "../models/schema.js";

/**
 * 🎫 Get guest passes generated by resident
 */
export async function getResidentGuestPasses(req: Request, res: Response, next: NextFunction) {
  try {
    if (!req.user || !req.societyId) {
      return res.status(401).json({ error: "Authentication required" });
    }

    const list = await db
      .select()
      .from(guestPasses)
      .where(
        and(
          eq(guestPasses.societyId, req.societyId),
          eq(guestPasses.residentId, req.user.id)
        )
      )
      .orderBy(desc(guestPasses.createdAt));

    return res.status(200).json({ guestPasses: list });
  } catch (error) {
    next(error);
  }
}

/**
 * ✍️ Create a pre-approved guest pass
 */
export async function createGuestPass(req: Request, res: Response, next: NextFunction) {
  try {
    if (!req.user || !req.societyId) {
      return res.status(401).json({ error: "Authentication required" });
    }

    const { guestName, validFrom, validTo } = req.body;

    if (!guestName) {
      return res.status(400).json({ error: "Guest name is required" });
    }

    // Generate secure 6-char token pass code
    const token = Math.random().toString(36).substring(2, 8).toUpperCase();

    const fromDate = validFrom ? new Date(validFrom) : new Date();
    const toDate = validTo ? new Date(validTo) : new Date(Date.now() + 86400000); // 24h validity fallback

    const [newPass] = await db
      .insert(guestPasses)
      .values({
        societyId: req.societyId,
        residentId: req.user.id,
        guestName: guestName.trim(),
        validFrom: fromDate,
        validTo: toDate,
        token,
        isUsed: false,
      })
      .returning();

    return res.status(201).json({
      message: "Pre-approved guest pass created successfully",
      guestPass: newPass,
    });
  } catch (error) {
    next(error);
  }
}

/**
 * 🔍 Verify and check-in QR / Passcode Guest Pass (Guard feature)
 */
export async function verifyGuestPass(req: Request, res: Response, next: NextFunction) {
  try {
    if (!req.user || !req.societyId) {
      return res.status(401).json({ error: "Authentication required" });
    }

    const { token } = req.body;

    if (!token || typeof token !== "string") {
      return res.status(400).json({ valid: false, error: "Pass code / token is required" });
    }

    const cleanToken = token.trim().toUpperCase();

    // Query pass
    const [pass] = await db
      .select()
      .from(guestPasses)
      .where(
        and(
          eq(guestPasses.societyId, req.societyId),
          eq(guestPasses.token, cleanToken)
        )
      );

    if (!pass) {
      return res.status(404).json({ valid: false, error: "Invalid Pass Code" });
    }

    if (pass.isUsed) {
      return res.status(400).json({ valid: false, error: "Pass Code has already been used" });
    }

    if (new Date() > new Date(pass.validTo)) {
      return res.status(400).json({ valid: false, error: "Pass Code has expired" });
    }

    // Get resident details
    const [resident] = await db
      .select()
      .from(user)
      .where(eq(user.id, pass.residentId));

    const flatNumber = resident?.flatNumber || "A-101";

    // Mark pass as used
    await db
      .update(guestPasses)
      .set({ isUsed: true })
      .where(eq(guestPasses.id, pass.id));

    // Automatically check visitor in
    const [newVisitor] = await db
      .insert(visitors)
      .values({
        societyId: req.societyId,
        flatNumber,
        name: pass.guestName,
        phone: "Pre-Approved Pass",
        purpose: "Guest Pass Entry",
        status: "checked_in",
        checkInTime: new Date(),
        approvedBy: pass.residentId,
      })
      .returning();

    return res.status(200).json({
      valid: true,
      message: "ACCESS GRANTED",
      pass,
      residentName: resident?.name || "Resident",
      flatNumber,
      visitor: newVisitor,
    });
  } catch (error) {
    next(error);
  }
}
