import { StyleSheet } from 'react-native';

export const sharedStyles = StyleSheet.create({
  scrollContent: {
    paddingBottom: 40,
    gap: 20,
  },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF5F5',
    borderWidth: 1,
    borderColor: '#FED7D7',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  errorIcon: {
    marginRight: 10,
  },
  errorText: {
    flex: 1,
    color: '#C53030',
    fontSize: 13,
    fontFamily: 'InterSemiBold',
    lineHeight: 18,
  },
  inputGroup: {
    gap: 8,
  },
  fieldLabel: {
    fontSize: 13.5,
    fontFamily: 'ManropeBold',
    fontWeight: 'bold',
    color: '#2D3748',
    letterSpacing: 0.1,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    paddingHorizontal: 16,
    height: 52,
    shadowColor: '#1A202C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 6,
    elevation: 1,
  },
  fieldIcon: {
    marginRight: 12,
  },
  textInput: {
    flex: 1,
    height: '100%',
    color: '#1A202C',
    fontSize: 14.5,
    fontFamily: 'InterMedium',
  },
  textAreaWrapper: {
    height: 120,
    alignItems: 'flex-start',
    paddingVertical: 12,
  },
  textArea: {
    flex: 1,
    width: '100%',
    height: '100%',
    color: '#1A202C',
    fontSize: 14.5,
    fontFamily: 'Inter',
    lineHeight: 20,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  categoryCard: {
    flex: 1,
    minWidth: '45%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    height: 48,
  },
  categoryText: {
    fontSize: 13,
    fontFamily: 'InterMedium',
    color: '#4A5568',
  },
  toggleCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 16,
    gap: 12,
  },
  toggleCardUrgent: {
    borderColor: '#FED7D7',
    backgroundColor: '#FFF5F5',
  },
  toggleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  toggleTitleWrapper: {
    flexDirection: 'row',
    gap: 12,
    flex: 1,
    paddingRight: 12,
  },
  toggleTextWrapper: {
    flex: 1,
  },
  toggleTitle: {
    fontSize: 14,
    fontFamily: 'ManropeBold',
    fontWeight: 'bold',
    color: '#2D3748',
  },
  toggleSubtitle: {
    fontSize: 11,
    fontFamily: 'Inter',
    color: '#71717A',
    lineHeight: 15,
    marginTop: 2,
  },
  urgentWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(229, 62, 62, 0.05)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  urgentWarningText: {
    fontSize: 11,
    fontFamily: 'InterMedium',
    color: '#C53030',
    flex: 1,
  },
  optionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 2,
  },
  addOptionLink: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(56, 161, 105, 0.08)',
  },
  addOptionLinkText: {
    fontSize: 12,
    fontFamily: 'InterBold',
    color: '#38A169',
    fontWeight: 'bold',
  },
  choiceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 2,
  },
  choiceNumberBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceNumberText: {
    fontSize: 11.5,
    fontFamily: 'InterBold',
    color: '#4A5568',
    fontWeight: 'bold',
  },
  choiceInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    paddingHorizontal: 16,
    height: 48,
  },
  choiceInput: {
    flex: 1,
    height: '100%',
    color: '#1A202C',
    fontSize: 14,
    fontFamily: 'InterMedium',
  },
  removeChoiceBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.03)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  questionInputWrapper: {
    height: 80,
    alignItems: 'flex-start',
    paddingVertical: 12,
  },
  questionInput: {
    flex: 1,
    width: '100%',
    height: '100%',
    color: '#1A202C',
    fontSize: 14.5,
    fontFamily: 'Inter',
    lineHeight: 20,
  },
  expirationGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  expirationCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: 'center',
    gap: 4,
  },
  expirationCardActive: {
    borderColor: '#38A169',
    backgroundColor: 'rgba(56, 161, 105, 0.05)',
  },
  expirationLabel: {
    fontSize: 13,
    fontFamily: 'ManropeBold',
    fontWeight: 'bold',
    color: '#4A5568',
    marginTop: 2,
  },
  expirationLabelActive: {
    color: '#38A169',
  },
  expirationDesc: {
    fontSize: 10,
    fontFamily: 'Inter',
    color: '#A3A1A8',
  },
  formFooter: {
    flexDirection: 'row',
    gap: 12,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#EDF2F7',
    backgroundColor: 'transparent',
  },
  cancelButton: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#EDF2F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    fontSize: 14,
    fontFamily: 'InterSemiBold',
    color: '#4A5568',
  },
  submitButton: {
    flex: 2,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#2E7D32',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  submitButtonText: {
    fontSize: 14,
    fontFamily: 'InterBold',
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
});
