import { Notice } from './types';

export const NOTICES: Notice[] = [
  {
    id: '1',
    category: 'Maintenance',
    title: 'Pool Cleaning & Water Treatment',
    description: 'The swimming pool will remain closed tomorrow from 10 AM to 2 PM for deep cleaning, sanitation, and water filtration system check.',
    content: 'Dear Residents,\n\nPlease be informed that the main swimming pool in Block B will be closed for quarterly scheduled maintenance and deep chemical treatment tomorrow.\n\nDuring this period, our maintenance staff will perform sanitation, PH level regulation, tile scrubbing, and filtration mesh replacement. Running the pool filtration during this chemical treatment is unsafe, hence the closure is mandatory.\n\nWe apologize for any inconvenience caused and appreciate your cooperation in keeping our community amenities clean and safe.\n\nFor any urgent queries, contact the Facilities Management Office at Ext. 402.',
    tag: 'Announcement',
    time: 'Tomorrow',
    date: '16 July 2026',
    author: 'Facilities Management',
    tagBg: 'rgba(245, 158, 11, 0.08)',
    tagBorder: 'rgba(245, 158, 11, 0.25)',
    tagText: '#B45309',
    iconName: 'megaphone',
    iconColor: '#B45309',
    isUrgent: false,
    isRead: false,
  },
  {
    id: '2',
    category: 'Society',
    title: 'Annual General Body Meeting 2026',
    description: 'The AGM has been rescheduled to this Sunday at 10 AM in the clubhouse. Attendance is highly requested.',
    content: 'Dear Resident Owners,\n\nThe Management Committee requests your presence at the Annual General Body Meeting (AGM) rescheduled for this Sunday in the Clubhouse Multi-Purpose Hall.\n\nAgenda items include:\n1. Reading & approval of the minutes of the previous AGM.\n2. Review of the audited financials for FY 2025-2026.\n3. Approval of the annual budget for the next financial year.\n4. Voting on proposed solar energy grid installation for common areas.\n5. Election of the new block representatives.\n\nRefreshments will be served after the meeting. If you are unable to attend, please submit your signed proxy form to the Society Office by Friday 5 PM.',
    tag: 'Official',
    time: '4 days ago',
    date: '11 July 2026',
    author: 'Society Committee',
    tagBg: 'rgba(46, 125, 50, 0.08)',
    tagBorder: 'rgba(46, 125, 50, 0.25)',
    tagText: '#2E7D32',
    iconName: 'shield-check',
    iconColor: '#2E7D32',
    isUrgent: true,
    isRead: false,
  },
  {
    id: '3',
    category: 'Events',
    title: 'Monsoon Music & Food Festival',
    description: 'Join us for food trucks, live music, and rain dance in the society lawns this Saturday at 6 PM! Entry is free.',
    content: 'Hello Residents!\n\nIt is time to celebrate the beautiful monsoon season! The Cultural Committee is hosting the Annual Monsoon Festival this Saturday at the Main Central Lawns.\n\nHighlights of the evening:\n- 4 Premium Food Trucks (tacos, dim sums, artisanal chaat, and waffle cones)\n- Live acoustic performance by local band "The Breezy Tunes"\n- DJ and Rain Dance arena (safe family zone)\n- Kids games and face painting stalls\n\nEntry is absolutely free for all residents and their registered guests. You can pre-register your guests on the Portl app to avoid gate queues. Let\'s gather for a night of food, music, and laughter!',
    tag: 'Event',
    time: 'In 2 days',
    date: '18 July 2026',
    author: 'Cultural Club',
    tagBg: 'rgba(14, 116, 144, 0.08)',
    tagBorder: 'rgba(14, 116, 144, 0.25)',
    tagText: '#0E7490',
    iconName: 'calendar',
    iconColor: '#0E7490',
    isUrgent: false,
    isRead: true,
  },
  {
    id: '4',
    category: 'Security',
    title: 'New Visitor Check-in Protocol',
    description: 'Effective next Monday, all delivery executives must complete QR pre-verification at the main gate.',
    content: 'Dear Residents,\n\nTo enhance the security of our residential complex, the security team is launching an upgraded digital gate check-in system starting next Monday.\n\nAll delivery executives (Zomato, Swiggy, Amazon, Flipkart, etc.) will be required to scan a gate QR code, and you will receive an instant approval prompt inside the Portl app. Pre-approved visitors will get immediate access, reducing wait times at the entrance.\n\nPlease ensure your visitor notifications are enabled in your settings. For frequent visitors (like domestic help or drivers), you can issue a reusable Resident-linked Guest Pass under the "Visitor" tab.\n\nThank you for helping us keep the community secure.',
    tag: 'Security Alert',
    time: '5 days ago',
    date: '10 July 2026',
    author: 'Security Department',
    tagBg: 'rgba(239, 68, 68, 0.08)',
    tagBorder: 'rgba(239, 68, 68, 0.25)',
    tagText: '#DC2626',
    iconName: 'alert-triangle',
    iconColor: '#DC2626',
    isUrgent: true,
    isRead: true,
  },
  {
    id: '5',
    category: 'Maintenance',
    title: 'Elevator Modernization (Block C)',
    description: 'Modernization of Lift #2 in Block C starts this Wednesday. Expect lift availability to be limited for 3 days.',
    content: 'Dear Block C Residents,\n\nWe will be upgrading and modernizing Lift #2 in Block C to improve safety, speed, and energy efficiency. The work is scheduled to start this Wednesday at 8 AM and is expected to be completed by Friday evening.\n\nLift #1 will remain fully operational during this period. However, expect slightly longer wait times during peak commute hours (8 AM - 10 AM, and 6 PM - 8 PM).\n\nIf you are moving heavy furniture or luggage, please coordinate with the security office in advance to use the service lift.\n\nThank you for your patience during these infrastructure upgrades.',
    tag: 'Announcement',
    time: 'In 3 days',
    date: '19 July 2026',
    author: 'Facilities Management',
    tagBg: 'rgba(245, 158, 11, 0.08)',
    tagBorder: 'rgba(245, 158, 11, 0.25)',
    tagText: '#B45309',
    iconName: 'megaphone',
    iconColor: '#B45309',
    isUrgent: false,
    isRead: true,
  }
];
